### ISSUE TITLE
Feature request: Custom appearance of the posframe

### ISSUE THREAD

**Issue by Yevgnen** [alexmurray/flycheck-posframe#11]
It would be nice to have the following things customizable:

1. The appearance of the posframe, e.g. border.

2. The position of the posframe, some thing like `lsp-ui` place the error message on the right side of the window is nice.

**Comment by dsvensson** [comment]
+1 on border just like lsp-ui, would be much easier to spot it. Doesn't seem to be customizable atm.

**Comment by alexmurray** [comment]
Please try using the new customization options in version 0.6 - `flycheck-posframe-position` `flycheck-posframe-border-width` and `flycheck-posframe-border-color` - hopefully these should meet your needs.
