### ISSUE TITLE
Don't show while auto-completion

### ISSUE THREAD

**Issue by seagle0128** [alexmurray/flycheck-posframe#12]
Thanks for the great package!

I have an issue while input with company. When auto-completion popup, the `flycheck-posframe` still popups, which overrides the company prompts. I think it should not display while auto-completion popups.

![image](https://user-images.githubusercontent.com/140797/54419018-068b2100-4739-11e9-8c31-0fa893be4ab4.png)

**Comment by alexmurray** [comment]
I can't reproduce this - it looks like you are using company-box - but even with that enabled I don't see this. Can you provide any more details how to reproduce it?

**Comment by seagle0128** [comment]
Thanks for the reply!

I think it's not related to `company-box`. I was trying to reproduce with vanilla Emacs, and found it occurred with `python-mode`, `flycheck-mode` and `lsp-mode`. Attached the recording below.

![emacs](https://user-images.githubusercontent.com/140797/55059113-18f64a80-50a9-11e9-9a0e-5e4019128706.gif)

**Comment by alexmurray** [comment]
Thanks - ok I have managed to reproduce it... I have just added a generic interface d1591cf which should allow you to relatively easily avoid this - with the latest git master you should be able to do the following:

    (add-to-list 'flycheck-posframe-inhibit-functions #'(lambda () company-backend)

Which will inhibit display of flycheck-posframe whenever company-backend is non-nil (which it is when company completion is active from what I can see).

Let me know what you think.

**Comment by seagle0128** [comment]
Perfect! It does work for me.

Suggest to make it as default value: `(lambda () (bound-and-true-p company-backend))`.

**Comment by sethen** [comment]
@alexmurray Any chance you can help me to do the same thing for corfu?  lol

**Comment by sethen** [comment]
@alexmurray Actually with some playing I found out that `corfu--candidates` variable did the trick.  Same thing as `company-backends` but corfu specific.

**Comment by alexmurray** [comment]
@sethen how about the following (untested):

```
(add-to-list 'flycheck-posframe-inhibit-functions #'(lambda () (and (bound-and-true-p corfu-mode) (bound-and-true-p completion-in-region-mode))))
```
