### ISSUE TITLE
Rendering of a posframe moves pointer to first line of frame

### ISSUE THREAD

**Issue by billywade** [alexmurray/flycheck-posframe#13]
Any time a new posframe is created, regardless of where it is on the screen, my pointer goes to the space just to the left of the first line in my existing buffer. I have no idea if this is a problem with this package or posframe itself.

Let me know what you need from me. Thanks!

**Comment by alexmurray** [comment]
Could you please capture a recording of this behaviour so I can better understand it?

Also can you reproduce it by just calling posframe directly - the following is an example to show a posframe taken from their README:

```
(when (posframe-workable-p)
  (posframe-show " *my-posframe-buffer*"
                 :string "This is a test"
                 :position (point)))
```

If it still occurs in this case, then I would assume it is a problem with posframe itself and hence to create a new issue in the upstream posframe project.

**Comment by billywade** [comment]
Gorgeous, it is an upstream issue, thank you.
