### ISSUE TITLE
Make a customizable face for flycheck content?

### ISSUE THREAD

**Issue by fuxialexander** [alexmurray/flycheck-posframe#2]
I'd like to change the display without modify the `flycheck-posframe-format-errors` function:
![image](https://user-images.githubusercontent.com/8258908/36932217-15d85404-1f01-11e8-9bb2-c20dccd4175e.png)

**Comment by alexmurray** [comment]
Added `flycheck-posframe-face` in 50ddda6 - does this suit your needs?

**Comment by fuxialexander** [comment]
@alexmurray It works. Thanks a lot!

**Comment by alexmurray** [comment]
No worries - you're welcome.
