### ISSUE TITLE
Posframe does not show up when using flycheck-next-error

### ISSUE THREAD

**Issue by fredmorcos** [alexmurray/flycheck-posframe#20]
When using `flycheck-next-error` (bound to `M-n`), `flycheck-posframe` doesn't show up, I have to move the cursor somewhere else then back on the error/warning area (without using `flycheck-next-error` or `M-n`) to get posframe to show up.

Here is a small config to reproduce it:

```elisp
;;; init --- Emacs configuration -*- lexical-binding: t; -*-
;;; Commentary:
;;; Code:

;; flycheck
(eval-when-compile (defvar flycheck-mode-map))
(autoload 'flycheck-next-error     "flycheck")
(autoload 'flycheck-previous-error "flycheck")
(add-hook 'flycheck-mode-hook
 (lambda ()
  (define-key flycheck-mode-map (kbd "M-n") #'flycheck-next-error)
  (define-key flycheck-mode-map (kbd "M-p") #'flycheck-previous-error)))

(add-hook 'prog-mode-hook #'flycheck-mode)

;; flycheck-posframe
(add-hook 'flycheck-mode-hook #'flycheck-posframe-mode)

(provide 'init)
;;; init ends here
```

**Comment by alexmurray** [comment]
Thanks for reporting this issue - I have a fix in the works that should be available for testing soon.

**Comment by fredmorcos** [comment]
I cannot wait to untrain my muscle memory.

**Comment by alexmurray** [comment]
Ok please see d9f97b008d1d13e046a31492ba57fc0b161bc1e7 which I just pushed :)

**Comment by fredmorcos** [comment]
> Ok please see [d9f97b0](https://github.com/alexmurray/flycheck-posframe/commit/d9f97b008d1d13e046a31492ba57fc0b161bc1e7) which I just pushed :)

Works great, thank you!

**Comment by alexmurray** [comment]
No worries - closing this issue :)
