### ISSUE TITLE
Feature request: padding/margin for frames

### ISSUE THREAD

**Issue by Bobbbay** [alexmurray/flycheck-posframe#29]
The border feature is awesome, but sadly looks very cramped for me:

![image](https://user-images.githubusercontent.com/49123594/122687442-85a71380-d1e4-11eb-8927-4e8e68ab2c12.png)

Is it possible to set a padding and/or margin for each frame? I can't seem to find the option :(. 

P.S. I have seen #11 but it doesn't seem to solve the spacing issue. 

Thanks in advance!

**Comment by woolsweater** [comment]
I find that I can fake padding acceptably using the `:box` face attribute, e.g.

```elisp
(let ((background some-color))
  (set-face-attribute 'flycheck-posframe-error-face nil 
                      :background background
                      :box `(:line-width (3 . 1) :color ,background)))
```
