### ISSUE TITLE
Package ‘emacs-26’ is unavailable

### ISSUE THREAD

**Issue by mambolevis** [alexmurray/flycheck-posframe#4]
Hi,

I'm using the following configuration to setup the package. 
```
(use-package flycheck-posframe     
  :ensure t
  :after flycheck
  :config (add-hook 'flycheck-mode-hook #'flycheck-posframe-mode))
```
Unfortunately,  the following message is depicted:
`"Package ‘emacs-26’ is unavailable"`

I checked `M-x package-list-packages`  and the package is marked as `incompat`, see bellow:
![image](https://user-images.githubusercontent.com/13024208/37197208-2961dbd0-237a-11e8-832c-6006bb1ba19d.png)

System Information:
- `GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2018-03-05`
- OS: `Windows 10`

**Comment by alexmurray** [comment]
emacs-26 means you need to be running emacs version >= 26 - but you are running emacs 25.3.1 - so hence why it is incompatible. All these packages use posframe which depends on the childframe functionality which is only in emacs >= 26.
