### ISSUE TITLE
Allow configuration of background

### ISSUE THREAD

**Issue by aaronjensen** [alexmurray/flycheck-posframe#6]
I'm not sure how, but it'd be great if we could customize the background color of the posframe. It currently matches the frame it is showing over, which makes it a bit harder to read.

If I customize the error/warning faces, I get this:

<img width="702" alt="cloudapp annotation 2018-03-11 at 10 01 20 am png" src="https://user-images.githubusercontent.com/8588/37256094-5a1df458-2513-11e8-83de-1ce2822c5d9c.png">

**Comment by alexmurray** [comment]
Let me know if https://github.com/alexmurray/flycheck-posframe/commit/93a8c590ac2275d754b4ca57f64e8335620ae789 solves this for you - you can customize `flycheck-posframe-background-face` - and the background of this face will be used for the background of the posframe frame.

**Comment by aaronjensen** [comment]
Seems to work for me. It doesn't play well w/ `auto-dim-other-buffers-mode`, but that's not the fault of this. I'll fix that elsewhere. Thanks!
