### ISSUE TITLE
posframe always opens over the minibuffer

### ISSUE THREAD

**Issue by CSRaghunandan** [alexmurray/flycheck-posframe#7]
Looks like the latest commit broke something? I'm getting the posframe popup over the minibuffer instead of below the cursor position

**Comment by alexmurray** [comment]
What emacs version are you running? I have noticed posframe is broken completely for me in current emacs-snapshot for the [Ubuntu elisp PPA](https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa) - also I haven't made any changes to flycheck-posframe that would affect positioning - so either this is a bug in Emacs itself or a bug in [posframe](https://github.com/tumashu/posframe).

**Comment by CSRaghunandan** [comment]
I am running emacs 26.091 devel release and I updated the packages flycheck-posframe broke. I also tried updating to emacs 27.0.50 and even it has same issue.

If if helps, I'm on MacOS Sierra.

**Comment by alexmurray** [comment]
Can you definitely confirm that it is broken if using the earlier version of flycheck-posframe but with the latest version of other packages? Since I can't reproduce I can't do a lot without more details...

**Comment by CSRaghunandan** [comment]
Sure, i'll with earlier version of flycheck-posframe and report the same after my day job is done. 

Thanks

**Comment by alexmurray** [comment]
Sorry for the delay in looking at this - I am not using MacOS and don't have easy access to it so it is hard for me to investigate - just for some more details - can you please confirm the last working version of flycheck-posframe? Also I just made a change to not always delete the posframe but to just hide it (specifically for an issue another user was having on MacOS - see issue #8) - so perhaps this will help you as well? Can you please try the current git version (or wait a day or so for MELPA to update to the latest) and let me know if that is any better?

**Comment by CSRaghunandan** [comment]
Okay just updated the package on MELPA and now the popup frame is opening in the right location!
Thanks for the fix

First invocation is still over the minibuffer, but after that, it's working as expected.
Also, I could never get posframe to work in fullscreen in mac. Each popup frame opens up in own fullscreen window for mac. But, I don't really use emacs in fullscreen mode.

**Comment by alexmurray** [comment]
I suggest for the remaining issues (wrongn initial placement and fullscreen woes) to open an issue in the posframe project itself - https://github.com/tumashu/posframe
