### ISSUE TITLE
Reuse frame instead of deleting and recreating

### ISSUE THREAD

**Issue by aaronjensen** [alexmurray/flycheck-posframe#8]
Hi, thanks again for flycheck-posframe. I'm wondering if it can be reworked slightly to reuse the posframe similar to how company-childframe does it. Every time a frame is created on macOS it causes a flicker in the top left of the parent frame. It's also slow, and worst of all, destroying the frame makes it far more likely to run into [bug#30800](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30800) which just outright crashes emacs when it happens.

**Comment by alexmurray** [comment]
Thanks - changed the behaviour to just hide the frame instead of deleting it in https://github.com/alexmurray/flycheck-posframe/commit/61bdfd4b04e1651163fdcaa7dc631ad073b3e513 - let me know if this works better for you.

**Comment by aaronjensen** [comment]
Awesome, thanks for the quick fix.
