### ISSUE TITLE
requires Emacs 26

### ISSUE THREAD

**Issue by hotpxl** [alexmurray/flycheck-posframe#9]
Is there any specific reason this needs Emacs 26?
Don't want to compile my own so stuck with 25.3 T_T

**Comment by alexmurray** [comment]
We depend on [posframe](https://github.com/tumashu/posframe) which requires Emacs 26 since it uses [child-frame](https://www.gnu.org/software/emacs/draft/manual/html_node/elisp/Child-Frames.html) which is only in Emacs 26.
